### ISSUE TITLE
刷新之后内容不会保留

### ISSUE THREAD

**Issue by dolphinfine** [yuzai/router-history#1]
有瑕疵啊老铁。刷新之后内容恢复成最原始状态s0k0了。前进后退是没有问题的。

**Comment by yuzai** [comment]
恩，对的。刷新的状态是没有保留的。因为每次刷新相当于从后台服务器拉取新的页面（这里就是github的静态页面），如果要保留状态，需要在服务器端进行保存。。。。当然，通过本地存储也是可以的，这个只是一个演示。。并没有做过多的处理。。。
